export const EVENT_UP_CREATE_GAME = 'up:game:create'
export const EVENT_UP_JOIN_GAME = 'up:game:join'
export const EVENT_UP_START_GAME = 'up:game:start'
export const EVENT_UP_GAME_TAP_BOMB = 'game:up:bomb:tap'
export const EVENT_UP_GAME_PASS_BOMB = 'game:up:bomb:pass'

export const EVENT_DOWN_PLAYER_JOINED = 'down:player:joined'
export const EVENT_DOWN_GAME_CREATED = 'down:game:created'
export const EVENT_DOWN_GAME_START = 'down:game:start'
export const EVENT_DOWN_GAME_TURN_START = 'down:game:turn:start'
