export default {
  CLIENT_CREATE_GAME: 'CLIENT_CREATE_GAME',
  CLIENT_JOIN_GAME: 'CLIENT_JOIN_GAME',
  CLIENT_START_GAME: 'CLIENT_START_GAME',
  CLIENT_GAME_TAP_BOMB: 'CLIENT_GAME_TAP_BOMB',
  CLIENT_GAME_PASS_BOMB: 'CLIENT_GAME_PASS_BOMBb'
}
